version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SECRET_KEY=change_this_to_a_secure_random_string
      - FLASK_APP=app
      - FLASK_ENV=production
      - DATABASE_URI=sqlite:///app.db
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: unless-stopped
    user: root  # Required to access Docker socket
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 